const VERIFIED_AT = "2026-07-21";

function freezeRows(rows) {
  return Object.freeze(rows.map((row) => Object.freeze({
    ...row,
    label: row.label || "大当り後の電サポ状態へ",
  })));
}

function weightedPayout(rows) {
  return Math.round(rows.reduce((total, row) => total + (row.payout * row.rate) / 100, 0) * 100) / 100;
}

function distributionLabel(rows) {
  return rows.map((row) => `${row.roundsLabel || `${row.rounds}R`}:${row.rate}%`).join(", ");
}

function freezeModes(modes) {
  return Object.freeze(modes.map((mode) => Object.freeze({
    ...mode,
    rows: freezeRows(mode.rows),
  })));
}

function createYutimeMachine({
  id,
  name,
  aliases = [],
  modelName,
  maker,
  type = "甘デジ",
  introductionDate,
  releaseStatus,
  synthProb,
  border1K,
  normalExpectedNetBalls,
  normalExpectedNetBallsMethod = "published-simulation",
  hesoRows,
  rushRows,
  rushEntryRate,
  rushContinueRate,
  stdDev,
  stdDevLabel,
  triggerLowSpins,
  durationSpins,
  durationLabel,
  expectedNetBalls,
  expectedNetBallsMethod = "published-simulation",
  benefit,
  sourceUrls,
  allocationNote,
  hesoModes,
  rushModes,
  extra = {},
}) {
  const frozenHesoRows = freezeRows(hesoRows);
  const frozenRushRows = freezeRows(rushRows);
  const primarySource = sourceUrls[0];
  const resolvedNormalExpectedNetBalls = normalExpectedNetBalls
    ?? Math.round((synthProb * 250 / border1K) * 100) / 100;
  const yutime = Object.freeze({
    triggerLowSpins,
    durationSpins,
    ...(durationLabel ? { durationLabel } : {}),
    expectedNetBalls,
    expectedNetBallsMethod,
    ...(benefit ? { benefit } : {}),
    sourceUrl: primarySource,
    verifiedAt: VERIFIED_AT,
    source: "reference",
  });

  return Object.freeze({
    id,
    name,
    aliases: Object.freeze(aliases),
    modelName,
    maker,
    type,
    introductionDate,
    ...(releaseStatus ? { releaseStatus } : {}),
    prob: `1/${synthProb}`,
    synthProb,
    border1K,
    border: Object.freeze({ "4.00": border1K }),
    spec1R: 90,
    specAvgTotalRounds: resolvedNormalExpectedNetBalls / 90,
    specSapo: 0,
    normalExpectedNetBalls: resolvedNormalExpectedNetBalls,
    normalExpectedNetBallsMethod,
    avgPayoutPerHit: weightedPayout(frozenHesoRows),
    hesoAvgPayout: weightedPayout(frozenHesoRows),
    rushAvgPayout: weightedPayout(frozenRushRows),
    rushEntryRate,
    rushContinueRate,
    stdDev,
    stdDevLabel,
    stdDevMethod: "p-evidence-branching-v2",
    roundDist: distributionLabel(frozenHesoRows),
    rushDist: distributionLabel(frozenRushRows),
    hesoDist: Object.freeze(frozenHesoRows.map(({ payout, rate }) => Object.freeze({ payout, rate }))),
    allocationVerified: true,
    hesoModes: hesoModes ? freezeModes(hesoModes) : freezeModes([{ name: "特図1・ヘソ", rows: hesoRows }]),
    rushModes: rushModes ? freezeModes(rushModes) : freezeModes([{ name: "特図2・右打ち中", rows: rushRows }]),
    allocationNote,
    sourceUrls: Object.freeze(sourceUrls),
    modelVerified: true,
    modelSourceUrl: primarySource,
    modelUpdatedAt: VERIFIED_AT,
    dataUpdatedAt: VERIFIED_AT,
    isYutimeReference: true,
    yutime,
    yutimeAudit: Object.freeze({
      status: "equipped",
      verifiedAt: VERIFIED_AT,
      sourceUrl: primarySource,
      note: `低確率${triggerLowSpins}回転消化で${durationLabel || `時短${durationSpins}回転`}`,
    }),
    ...extra,
  });
}

const machine = createYutimeMachine;

// 2024～2026年導入（予定を含む）の遊タイム搭載機。
// 平均獲得玉は公開シミュレーション値を優先し、見当たらない機種だけ振り分け分岐から算出しています。
export const yutimeReferenceMachines = Object.freeze([
  machine({
    id: "yutime-ref-garo-gekideji",
    name: "PA激デジ牙狼 月虹ノ旅人",
    aliases: ["PA激デジ牙狼", "牙狼 甘デジ", "牙狼 月虹 77"],
    modelName: "PA激デジ牙狼月虹ノ旅人-RL",
    maker: "サンセイR&D",
    introductionDate: "2024-01-09",
    synthProb: 77.74,
    border1K: 14.67,
    normalExpectedNetBalls: 1230.08,
    hesoRows: [
      { rounds: 10, payout: 800, rate: 0.8, label: "魔戒CHANCEへ" },
      { rounds: 3, payout: 240, rate: 99.2, label: "50回転のチャンス区間へ" },
    ],
    rushRows: [
      { rounds: 10, payout: 800, rate: 30.5, label: "魔戒CHANCE継続" },
      { rounds: 5, payout: 400, rate: 69.5, label: "魔戒CHANCE継続" },
    ],
    rushEntryRate: 50.3,
    rushContinueRate: 75.24,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST100回＋時短50回・右10R30.5%型）",
    triggerLowSpins: 233,
    durationSpins: 295,
    expectedNetBalls: 1898.24,
    sourceUrls: ["https://pachinko-spec.info/spec/132800/", "https://pachinko-spec.info/spec-detail/132799/"],
    allocationNote: "出玉は払い出し。初当り後の時短50回と、右打ちST100回の分岐を分けて平均・標準偏差を算出します。",
  }),
  machine({
    id: "yutime-ref-lupin99",
    name: "Pルパン三世 THE FIRST 99ver.",
    aliases: ["Pルパン99", "ルパン THE FIRST 99"],
    modelName: "Pルパン三世真速9YS1Y",
    maker: "平和",
    introductionDate: "2024-02-19",
    synthProb: 99.9,
    border1K: 15.85,
    normalExpectedNetBalls: 1066.15,
    hesoRows: [{ rounds: 10, payout: 800, rate: 0.5 }, { rounds: 3, payout: 240, rate: 99.5 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 50 }, { rounds: 3, payout: 240, rate: 50 }],
    rushEntryRate: 41.92,
    rushContinueRate: 65.36,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST＋時短突破・右10R50%型）",
    triggerLowSpins: 164,
    durationSpins: 379,
    expectedNetBalls: 1517.92,
    sourceUrls: ["https://pachinko-spec.info/spec/134951/", "https://pachinko-spec.info/spec-detail/134950/"],
    allocationNote: "出玉は払い出し。右打ち中は10Rと3Rが各50%です。",
  }),
  machine({
    id: "yutime-ref-fujiko89",
    name: "PAルパン三世 THE FIRST 不二子89ver.",
    aliases: ["PAルパン不二子89", "不二子89"],
    modelName: "PAルパン三世真速89GO1",
    maker: "平和",
    introductionDate: "2024-02-19",
    synthProb: 89.9,
    border1K: 15.78,
    normalExpectedNetBalls: 1062.76,
    hesoRows: [{ rounds: 10, payout: 800, rate: 0.5 }, { rounds: 4, payout: 320, rate: 99.5 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 25 }, { rounds: 4, payout: 320, rate: 75 }],
    rushEntryRate: 38.87,
    rushContinueRate: 74.8,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST＋時短突破・右10R25%型）",
    triggerLowSpins: 164,
    durationSpins: 316,
    expectedNetBalls: 1560.69,
    sourceUrls: ["https://pachinko-spec.info/spec/137717/", "https://pachinko-spec.info/spec-detail/137716/"],
    allocationNote: "出玉は払い出し。設定1の大当り確率・ボーダーを登録しています。",
  }),
  machine({
    id: "yutime-ref-mankai-mukashibanashi",
    name: "PA満開昔ばなし 天まで届け100ver.",
    aliases: ["PA満開昔ばなし", "満開昔ばなし100"],
    modelName: "PA満開昔ばなし天まで届け100ver.GO",
    maker: "豊丸",
    introductionDate: "2024-03-04",
    synthProb: 66.6,
    border1K: 19.3,
    normalExpectedNetBalls: 862.69,
    normalExpectedNetBallsMethod: "border-derived",
    hesoRows: [
      { rounds: 3, payout: 210, rate: 4.7, label: "満開RUSHへ" },
      { rounds: 3, payout: 210, rate: 93, label: "通常へ" },
      { rounds: 3, payout: 210, rate: 2.3, label: "突然時短へ" },
    ],
    rushRows: [{ rounds: 9, payout: 630, rate: 10.2 }, { rounds: 3, payout: 210, rate: 89.8 }],
    rushEntryRate: 4.7,
    rushContinueRate: 86.8,
    stdDev: 9000,
    stdDevLabel: "P-EVIDENCE推定（高継続RUSH・突然時短分岐型）",
    triggerLowSpins: 100,
    durationSpins: 10000,
    expectedNetBalls: 1723.91,
    expectedNetBallsMethod: "allocation-derived",
    sourceUrls: ["https://www.toyomaru.jp/machine/2024y/pa100vergo.html", "https://pachiseven.jp/machines/6916"],
    allocationNote: "出玉は払い出し。遊タイム平均獲得玉は右打ち実獲得（払い出しの90%）と継続率86.8%から分岐計算しています。",
  }),
  machine({
    id: "yutime-ref-seven-virtues",
    name: "P七つの美徳 ゴールデンエンジェルタイム",
    aliases: ["P七つの美徳", "七つの美徳99"],
    modelName: "P七つの美徳V2A",
    maker: "高尾",
    introductionDate: "2024-08-19",
    synthProb: 99.91,
    border1K: 17.68,
    normalExpectedNetBalls: 1312.51,
    hesoRows: [{ rounds: 4, payout: 360, rate: 100 }],
    rushRows: [{ rounds: 7, payout: 630, rate: 34.1 }, { rounds: 4, payout: 360, rate: 65.9 }],
    rushEntryRate: 70.05,
    rushContinueRate: 70.05,
    stdDev: 9000,
    stdDevLabel: "P-EVIDENCE推定（上位時短299回分岐・右7R34.1%型）",
    triggerLowSpins: 299,
    durationSpins: 379,
    expectedNetBalls: 1406.19,
    sourceUrls: ["https://pachinko-spec.info/spec/142716/", "https://pachinko-spec.info/spec-detail/142715/"],
    allocationNote: "出玉は払い出し。右打ちの時短回数分岐は別状態として標準偏差へ反映しています。",
  }),
  machine({
    id: "yutime-ref-komakoma-loop1",
    name: "PAコマコマ倶楽部with坂本冬美 LOOP1",
    aliases: ["PAコマコマLOOP1", "コマコマ倶楽部 LOOP1"],
    modelName: "PAコマコマ倶楽部with坂本冬美LOOP1",
    maker: "豊丸",
    introductionDate: "2024-08-19",
    synthProb: 99.9,
    border1K: 18.08,
    normalExpectedNetBalls: 1239.19,
    hesoRows: [
      { rounds: 10, payout: 800, rate: 10, label: "確変" },
      { rounds: 5, payout: 400, rate: 40, label: "確変" },
      { rounds: 5, payout: 400, rate: 4, label: "通常・長時短" },
      { rounds: 5, payout: 400, rate: 46, label: "通常" },
    ],
    rushRows: [{ rounds: 10, payout: 800, rate: 10 }, { rounds: 5, payout: 400, rate: 90 }],
    rushEntryRate: 68.93,
    rushContinueRate: 68.93,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（確変ループ＋通常時短分岐型）",
    triggerLowSpins: 265,
    durationSpins: 9999,
    expectedNetBalls: 1239.13,
    sourceUrls: ["https://pachinko-spec.info/spec/143103/", "https://pachinko-spec.info/spec-detail/143102/"],
    allocationNote: "出玉は払い出し。確変・通常時短の遷移を分けて標準偏差を見積もっています。",
  }),
  machine({
    id: "yutime-ref-wanwan-celebration99",
    name: "PAわんわんパラダイスCELEBRATION",
    aliases: ["PAわんわんセレブレーション", "わんわんCELEBRATION 99"],
    modelName: "PAわんわんセレブレーションAGBD",
    maker: "三洋",
    introductionDate: "2024-10-07",
    synthProb: 99.9,
    border1K: 14.75,
    normalExpectedNetBalls: 1502.35,
    hesoRows: [{ rounds: 10, payout: 800, rate: 3 }, { rounds: 6, payout: 480, rate: 53 }, { rounds: 4, payout: 320, rate: 44 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 22 }, { rounds: 6, payout: 480, rate: 39 }, { rounds: 4, payout: 320, rate: 39 }],
    rushEntryRate: 41.92,
    rushContinueRate: 89.63,
    stdDev: 10000,
    stdDevLabel: "P-EVIDENCE推定（下位RUSH＋上位約90%継続分岐型）",
    triggerLowSpins: 250,
    durationSpins: 379,
    expectedNetBalls: 2375.06,
    sourceUrls: ["https://pachinko-spec.info/spec/144208/", "https://pachinko-spec.info/spec-detail/144207/"],
    allocationNote: "出玉は払い出し。下位RUSHと上位CELEBRATIONを別状態として扱います。",
  }),
  machine({
    id: "yutime-ref-akina-ai",
    name: "P中森明菜・歌姫伝説 愛 99ver.",
    aliases: ["中森明菜 愛", "歌姫伝説 愛"],
    modelName: "P中森明菜・歌姫伝説愛KD-NS",
    maker: "D-light",
    introductionDate: "2024-10-07",
    synthProb: 99.9,
    border1K: 16.88,
    normalExpectedNetBalls: 1152.7,
    hesoRows: [{ rounds: 10, payout: 1000, rate: 1 }, { rounds: 4, payout: 400, rate: 99 }],
    rushRows: [{ rounds: 10, payout: 1000, rate: 20 }, { rounds: 4, payout: 400, rate: 70 }, { rounds: 2, payout: 200, rate: 10 }],
    rushEntryRate: 63.07,
    rushContinueRate: 63.07,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST100%・右10R20%型）",
    triggerLowSpins: 150,
    durationSpins: 50000,
    expectedNetBalls: 1218.84,
    sourceUrls: ["https://pachinko-spec.info/spec/143505/", "https://pachinko-spec.info/spec-detail/143504/"],
    allocationNote: "出玉は払い出し。全大当り後STのラウンド分岐を登録しています。",
  }),
  machine({
    id: "yutime-ref-akina-raku",
    name: "P中森明菜・歌姫伝説 楽 89ver.",
    aliases: ["中森明菜 楽", "歌姫伝説 楽"],
    modelName: "P中森明菜・歌姫伝説楽KD-KT",
    maker: "D-light",
    introductionDate: "2024-10-07",
    synthProb: 89.91,
    border1K: 17.4,
    normalExpectedNetBalls: 1188.91,
    hesoRows: [{ rounds: 10, payout: 800, rate: 5 }, { rounds: 5, payout: 400, rate: 95 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 25 }, { rounds: 5, payout: 400, rate: 75, label: "2R表示を含む5R相当払い出し" }],
    rushEntryRate: 65.09,
    rushContinueRate: 65.09,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST100%・右10R25%型）",
    triggerLowSpins: 230,
    durationSpins: 50000,
    expectedNetBalls: 1252.39,
    sourceUrls: ["https://pachinko-spec.info/spec/154317/", "https://pachinko-spec.info/spec-detail/154316/"],
    allocationNote: "出玉は払い出し。2R表示の枝は公開計算上の5R相当払い出しに統合しています。",
  }),
  machine({
    id: "yutime-ref-nanashi-oedo",
    name: "PAナナシーお江戸ver.",
    aliases: ["PAナナシーお江戸", "ナナシー77"],
    modelName: "PAナナシーお江戸ver.V2",
    maker: "豊丸",
    introductionDate: "2024-11-05",
    synthProb: 77.4,
    border1K: 16.99,
    normalExpectedNetBalls: 956.85,
    hesoRows: [{ rounds: 10, payout: 800, rate: 15 }, { rounds: 4, payout: 320, rate: 85 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 30.1 }, { rounds: 4, payout: 320, rate: 69.9 }],
    rushEntryRate: 59.77,
    rushContinueRate: 59.77,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（ST100%・右10R30.1%型）",
    triggerLowSpins: 180,
    durationSpins: 9999,
    expectedNetBalls: 1010.15,
    sourceUrls: ["https://pachinko-spec.info/spec/154337/", "https://pachinko-spec.info/spec-detail/154336/"],
    allocationNote: "出玉は払い出し。発動条件は低確率180回転です（シミュレーション上のTS141回とは区別）。",
  }),
  machine({
    id: "yutime-ref-gogo-go5",
    name: "P GO! GO! 郷 豪遊の5",
    aliases: ["P GO GO 郷", "豪遊の5"],
    modelName: "PGO！GO！郷～豪遊の5～N-VYLT",
    maker: "ニューギン",
    type: "甘デジLT",
    introductionDate: "2024-12-02",
    synthProb: 99.9,
    border1K: 18.7,
    normalExpectedNetBalls: 1335.56,
    normalExpectedNetBallsMethod: "border-derived",
    hesoRows: [{ rounds: 5, payout: 250, rate: 100 }],
    rushRows: [{ rounds: 10, payout: 840, rate: 67 }, { rounds: 2, payout: 100, rate: 33 }],
    rushEntryRate: 51,
    rushContinueRate: 92.3,
    stdDev: 14000,
    stdDevLabel: "P-EVIDENCE推定（遊タイムLT直行・上位約92.3%継続型）",
    triggerLowSpins: 299,
    durationSpins: 10000,
    durationLabel: "実質次回大当りまで",
    expectedNetBalls: 6963.9,
    expectedNetBallsMethod: "allocation-derived",
    benefit: "最上位LT『LUCKY GO! GO! RUSH』へ直行",
    sourceUrls: ["https://www.p-world.co.jp/machine/database/10172", "https://pachiseven.jp/machines_v2/7071"],
    allocationNote: "出玉は払い出し。下位RUSHと上位LTを別状態にし、遊タイム平均は実獲得90%と上位継続率から分岐計算しています。",
    rushModes: [
      { name: "GO! GO! RUSH", rows: [{ rounds: 10, payout: 840, rate: 0.3, label: "LTへ" }, { rounds: 10, payout: 840, rate: 66.7, label: "下位継続" }, { rounds: 2, payout: 100, rate: 33, label: "終了" }] },
      { name: "LUCKY GO! GO! RUSH", rows: [{ rounds: 10, payout: 840, rate: 67, label: "上位継続" }, { rounds: 2, payout: 100, rate: 24.4, label: "上位継続" }, { rounds: 2, payout: 100, rate: 8.6, label: "終了" }] },
    ],
  }),
  machine({
    id: "yutime-ref-natsuiro",
    name: "eA夏色日記",
    aliases: ["夏色日記", "eA夏色日記 GO"],
    modelName: "eA夏色日記GO",
    maker: "豊丸",
    type: "スマパチ甘デジ",
    introductionDate: "2024-12-16",
    synthProb: 89.81,
    border1K: 16.8,
    normalExpectedNetBalls: 1170.33,
    hesoRows: [{ rounds: 5, payout: 450, rate: 50, label: "確変" }, { rounds: 5, payout: 450, rate: 50, label: "通常・時短30回" }],
    rushRows: [{ rounds: 5, payout: 450, rate: 50, label: "確変" }, { rounds: 5, payout: 450, rate: 50, label: "通常・時短30回" }],
    rushEntryRate: 65.82,
    rushContinueRate: 65.82,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（確変50%ループ＋時短30回型）",
    triggerLowSpins: 220,
    durationSpins: 10000,
    expectedNetBalls: 1169.96,
    sourceUrls: ["https://pachinko-spec.info/spec/154331/", "https://pachinko-spec.info/spec-detail/154329/"],
    allocationNote: "出玉は払い出し。設定1の確率と確変・通常時短の遷移を登録しています。",
  }),
  machine({
    id: "yutime-ref-keiji-retsu99",
    name: "PA花の慶次～裂 99ver.",
    aliases: ["PA花の慶次 裂99", "甘慶次 裂"],
    modelName: "PA花の慶次～裂N3-VY",
    maker: "ニューギン",
    introductionDate: "2025-01-20",
    synthProb: 99.9,
    border1K: 16.32,
    normalExpectedNetBalls: 1391.49,
    hesoRows: [{ rounds: 10, payout: 800, rate: 0.5 }, { rounds: 3, payout: 240, rate: 99.5 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 50.1 }, { rounds: 5, payout: 400, rate: 49.9 }],
    rushEntryRate: 40.6,
    rushContinueRate: 79.75,
    stdDev: 10000,
    stdDevLabel: "P-EVIDENCE推定（時短突破＋右10R50.1%型）",
    triggerLowSpins: 299,
    durationSpins: 1000,
    durationLabel: "実質次回大当りまで",
    expectedNetBalls: 2593.11,
    sourceUrls: ["https://pachinko-spec.info/spec/149436/", "https://pachinko-spec.info/spec-detail/149435/"],
    allocationNote: "出玉は払い出し。右打ちの10R・5R分岐と電サポ状態を分けています。",
  }),
  machine({
    id: "yutime-ref-shin-eva99-goraku",
    name: "PAシン・エヴァンゲリオン 99 ごらくver.",
    aliases: ["PAシンエヴァ99", "シンエヴァ ごらく"],
    modelName: "PAシン・エヴァンゲリオンGO",
    maker: "ビスティ",
    introductionDate: "2025-02-03",
    synthProb: 99.9,
    border1K: 16.5,
    normalExpectedNetBalls: 1391.43,
    hesoRows: [{ rounds: 10, payout: 800, rate: 1 }, { rounds: 5, payout: 400, rate: 99 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 50 }, { rounds: 5, payout: 400, rate: 50 }],
    rushEntryRate: 51.55,
    rushContinueRate: 76.05,
    stdDev: 9000,
    stdDevLabel: "P-EVIDENCE推定（時短突破＋右10R50%型）",
    triggerLowSpins: 299,
    durationSpins: 10000,
    expectedNetBalls: 2190.95,
    sourceUrls: ["https://pachinko-spec.info/spec/154346/", "https://pachinko-spec.info/spec-detail/154345/", "https://www.dynam.jp/news/pdf/news_250114.pdf"],
    allocationNote: "出玉は払い出し。遊タイム到達後は電チュー大当りの右打ち振り分けへ移行します。",
  }),
  machine({
    id: "yutime-ref-winter-sonata-goraku",
    name: "P冬のソナタ My Memory Sweet GORAKU Version",
    aliases: ["P冬ソナ My Memory", "冬ソナ Sweet ごらく"],
    modelName: "P冬のソナタMyMemoryG2",
    maker: "京楽",
    introductionDate: "2025-02-03",
    synthProb: 99.9,
    border1K: 17.39,
    normalExpectedNetBalls: 1166.51,
    hesoRows: [{ rounds: 7, payout: 441, rate: 80 }, { rounds: 2, payout: 6, rate: 20 }],
    rushRows: [{ rounds: 7, payout: 441, rate: 90 }, { rounds: 2, payout: 6, rate: 10 }],
    rushEntryRate: 60,
    rushContinueRate: 60,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（MAX8合算・確変ループ型）",
    triggerLowSpins: 200,
    durationSpins: 10000,
    expectedNetBalls: 1197.49,
    sourceUrls: ["https://pachinko-spec.info/spec/154324/", "https://pachinko-spec.info/spec-detail/154323/"],
    allocationNote: "出玉は払い出し。通常時は特図1・特図2が交互に回るMAX8の合算振り分けです。",
  }),
  machine({
    id: "yutime-ref-higurashi99",
    name: "PAひぐらしのなく頃に 輪廻転生99ver.",
    aliases: ["PAひぐらし輪廻転生99", "ひぐらし99 遊タイム"],
    modelName: "PAひぐらしのなく頃に・輪廻転生99FD-TH",
    maker: "大一",
    introductionDate: "2025-03-17",
    synthProb: 99.9,
    border1K: 16.15,
    normalExpectedNetBalls: 1338.23,
    hesoRows: [{ rounds: 4, payout: 360, rate: 100 }],
    rushRows: [{ rounds: 10, payout: 900, rate: 20 }, { rounds: 4, payout: 360, rate: 80 }],
    rushEntryRate: 62.67,
    rushContinueRate: 72.7,
    stdDev: 9000,
    stdDevLabel: "P-EVIDENCE推定（時短突破＋右10R20%型）",
    triggerLowSpins: 199,
    durationSpins: 10000,
    durationLabel: "実質次回大当りまで",
    expectedNetBalls: 1530.56,
    sourceUrls: ["https://pachinko-spec.info/spec/153192/", "https://pachinko-spec.info/spec-detail/153191/"],
    allocationNote: "出玉は払い出し。遊タイム到達時はRUSH突入が濃厚です。",
  }),
  machine({
    id: "yutime-ref-komakoma89st",
    name: "PAコマコマ倶楽部 with 坂本冬美 89STver.",
    aliases: ["PAコマコマ89ST", "コマコマ坂本冬美89"],
    modelName: "PAコマコマ倶楽部with坂本冬美VS1",
    maker: "豊丸",
    introductionDate: "2025-07-22",
    synthProb: 89.78,
    border1K: 17.65,
    normalExpectedNetBalls: 1165.17,
    hesoRows: [{ rounds: 10, payout: 800, rate: 34 }, { rounds: 5, payout: 400, rate: 66 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 34 }, { rounds: 5, payout: 400, rate: 66 }],
    rushEntryRate: 59.3,
    rushContinueRate: 59.3,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（ST100%・電サポ回数分岐型）",
    triggerLowSpins: 265,
    durationSpins: 9999,
    expectedNetBalls: 1165.48,
    sourceUrls: ["https://pachinko-spec.info/spec/158623/", "https://pachinko-spec.info/spec-detail/158621/"],
    allocationNote: "出玉は払い出し。設定1の値で、複数の電サポ回数を分岐として扱います。",
  }),
  machine({
    id: "yutime-ref-yasei6",
    name: "PA野生の王国Ⅵ",
    aliases: ["PA野生の王国6", "野生の王国6 甘"],
    modelName: "PA野生の王国6N2",
    maker: "ニューギン",
    introductionDate: "2025-12-08",
    synthProb: 99.9,
    border1K: 16.79,
    normalExpectedNetBalls: 1390.69,
    hesoRows: [{ rounds: 5, payout: 500, rate: 55 }, { rounds: 4, payout: 400, rate: 45 }],
    rushRows: [{ rounds: 10, payout: 1000, rate: 10 }, { rounds: 5, payout: 500, rate: 48 }, { rounds: 4, payout: 400, rate: 42 }],
    rushEntryRate: 64.5,
    rushContinueRate: 72.58,
    stdDev: 9000,
    stdDevLabel: "P-EVIDENCE推定（複数RUSH状態＋右10R10%型）",
    triggerLowSpins: 299,
    durationSpins: 5000,
    expectedNetBalls: 1478.79,
    benefit: "百獣の王TIME(∞)へ突入",
    sourceUrls: ["https://pachinko-spec.info/spec/163252/", "https://pachinko-spec.info/spec-detail/163251/"],
    allocationNote: "出玉は払い出し。通常RUSHと上位状態の継続差を標準偏差へ反映しています。",
  }),
  machine({
    id: "yutime-ref-hanahai49",
    name: "P華牌RR 1/49×99de遊タイム",
    aliases: ["華牌RR", "華牌 1/49 99遊タイム"],
    modelName: "P華牌RRAX5",
    maker: "豊丸",
    type: "甘デジLT",
    introductionDate: "2026-01-05",
    synthProb: 49.91,
    border1K: 16.75,
    normalExpectedNetBalls: 616.56,
    hesoRows: [{ rounds: 5, payout: 200, rate: 0.8 }, { rounds: 4, payout: 160, rate: 5.5 }, { rounds: 3, payout: 120, rate: 11.3 }, { rounds: 2, payout: 80, rate: 82.4 }],
    rushRows: [{ rounds: 5, payout: 450, rate: 1.2 }, { rounds: 4, payout: 360, rate: 33.2 }, { rounds: 3, payout: 270, rate: 32.8 }, { rounds: 2, payout: 180, rate: 32.8 }],
    rushEntryRate: 65.4,
    rushContinueRate: 65.4,
    stdDev: 11000,
    stdDevLabel: "P-EVIDENCE推定（段階上位移行・最上位約96.35%継続型）",
    triggerLowSpins: 99,
    durationSpins: 10000,
    expectedNetBalls: 1244.28,
    sourceUrls: ["https://pachinko-spec.info/spec/164133/", "https://pachinko-spec.info/spec-detail/164132/"],
    allocationNote: "出玉は払い出し。通常・上位・最上位のモード昇格を別状態として標準偏差へ反映しています。",
  }),
  machine({
    id: "yutime-ref-norimonomusume77",
    name: "PA乗物娘 WITH CJD 2nd season 77ver.",
    aliases: ["PA乗物娘77", "乗物娘2 77"],
    modelName: "PA乗物娘2N",
    maker: "ニューギン",
    introductionDate: "2026-02-02",
    synthProb: 77.1,
    border1K: 16.2,
    normalExpectedNetBalls: 1032.59,
    hesoRows: [{ rounds: 10, payout: 1000, rate: 15.5 }, { rounds: 4, payout: 400, rate: 84.5 }],
    rushRows: [{ rounds: 10, payout: 1000, rate: 30 }, { rounds: 4, payout: 400, rate: 70 }],
    rushEntryRate: 52.57,
    rushContinueRate: 52.57,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（MAX8合算・ST100%型）",
    triggerLowSpins: 159,
    durationSpins: 10000,
    expectedNetBalls: 1100.21,
    sourceUrls: ["https://pachinko-spec.info/spec/165113/", "https://pachinko-spec.info/spec-detail/165112/"],
    allocationNote: "出玉は払い出し。通常時はMAX8（特図1と特図2）の合算振り分けで、平均493発です。",
  }),
  machine({
    id: "yutime-ref-norimonomusume59",
    name: "PA乗物娘 2nd season 59ver.",
    aliases: ["PA乗物娘59", "乗物娘2 59"],
    modelName: "PA乗物娘2GO2",
    maker: "ニューギン",
    introductionDate: "2026-02-02",
    synthProb: 59.9,
    border1K: 17.5,
    normalExpectedNetBalls: 862.07,
    normalExpectedNetBallsMethod: "allocation-derived",
    hesoRows: [{ rounds: 10, payout: 700, rate: 26.5 }, { rounds: 4, payout: 280, rate: 73.5 }],
    rushRows: [{ rounds: 10, payout: 700, rate: 52 }, { rounds: 4, payout: 280, rate: 48 }],
    rushEntryRate: 53.2,
    rushContinueRate: 53.2,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（MAX8合算・右10R52%型）",
    triggerLowSpins: 160,
    durationSpins: 10000,
    expectedNetBalls: 958.5,
    expectedNetBallsMethod: "allocation-derived",
    sourceUrls: ["https://www.dynam.jp/news/pdf/news_260203.pdf", "https://1geki.jp/pachinko/pa_norimonom2_59/"],
    allocationNote: "出玉は払い出し。公式訂正資料どおり発動は低確率160回転。遊タイム平均は実獲得90%と継続率から算出しています。",
  }),
  machine({
    id: "yutime-ref-planet-apollo",
    name: "eAぷらねっとアポロGO",
    aliases: ["ぷらねっとアポロ", "アポロGO"],
    modelName: "eAぷらねっとアポロGO2-X",
    maker: "豊丸",
    type: "スマパチ甘デジ",
    introductionDate: "2026-02-02",
    synthProb: 99.9,
    border1K: 20.5,
    normalExpectedNetBalls: 1167.41,
    normalExpectedNetBallsMethod: "allocation-derived",
    hesoRows: [{ rounds: 10, payout: 900, rate: 5 }, { rounds: 5, payout: 450, rate: 56 }, { rounds: 3, payout: 270, rate: 39 }],
    rushRows: [{ rounds: 10, payout: 900, rate: 9 }, { rounds: 5, payout: 450, rate: 50 }, { rounds: 3, payout: 270, rate: 41 }],
    rushEntryRate: 58.1,
    rushContinueRate: 80.3,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST8回＋時短25/50/100回ループ型）",
    triggerLowSpins: 242,
    durationSpins: 10000,
    expectedNetBalls: 1206.6,
    expectedNetBallsMethod: "allocation-derived",
    sourceUrls: ["https://www.dynam.jp/pb/machine/ea_planet_apollo_go/", "https://1geki.jp/pachinko/ea_planetapollo/", "https://p.hisshobon.jp/machine/4686/1/113488"],
    allocationNote: "設定1・払い出し。遊タイム平均は10R後の電サポ100回ループと、3R後25回・5R後50回の再帰分岐を実獲得90%で計算しています。",
    rushModes: [
      { name: "スペースチャンスタイム25/50回", rows: [{ rounds: 10, payout: 900, rate: 9, label: "超スペース100回へ" }, { rounds: 5, payout: 450, rate: 50, label: "50回へ" }, { rounds: 3, payout: 270, rate: 41, label: "25回へ" }] },
      { name: "超スペースチャンスタイム100回", rows: [{ rounds: 10, payout: 900, rate: 9, label: "100回継続" }, { rounds: 5, payout: 450, rate: 50, label: "100回継続" }, { rounds: 3, payout: 270, rate: 41, label: "100回継続" }] },
    ],
  }),
  machine({
    id: "yutime-ref-komakoma89-loop",
    name: "PAコマコマ倶楽部 89確変ループ10R極",
    aliases: ["PAコマコマ89 10R極", "コマコマ確変ループ"],
    modelName: "PAコマコマ倶楽部with坂本冬美VLP1",
    maker: "豊丸",
    introductionDate: "2026-04-06",
    synthProb: 89.81,
    border1K: 17.8,
    normalExpectedNetBalls: 1166.39,
    hesoRows: [{ rounds: 10, payout: 800, rate: 5.9 }, { rounds: 5, payout: 400, rate: 94.1 }],
    rushRows: [{ rounds: 10, payout: 800, rate: 5.9 }, { rounds: 5, payout: 400, rate: 94.1 }],
    rushEntryRate: 63.5,
    rushContinueRate: 63.5,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（確変ループ＋通常時短・10R5.9%型）",
    triggerLowSpins: 265,
    durationSpins: 9999,
    expectedNetBalls: 1166.85,
    sourceUrls: ["https://pachinko-spec.info/spec/167571/", "https://pachinko-spec.info/spec-detail/167570/"],
    allocationNote: "設定1・払い出し。確変ループと通常時短の遷移を別状態として扱います。",
  }),
  machine({
    id: "yutime-ref-kabuki87",
    name: "PA花の慶次～傾奇一転 87ver.",
    aliases: ["PA花慶87", "傾奇一転87"],
    modelName: "PA花の慶次～傾奇一転N",
    maker: "ニューギン",
    introductionDate: "2026-06-08",
    synthProb: 87.84,
    border1K: 16.29,
    normalExpectedNetBalls: 1178.64,
    hesoRows: [{ rounds: 10, payout: 1000, rate: 1 }, { rounds: 4, payout: 400, rate: 99 }],
    rushRows: [{ rounds: 10, payout: 1000, rate: 33 }, { rounds: 4, payout: 400, rate: 67 }],
    rushEntryRate: 59.52,
    rushContinueRate: 59.52,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（ST＋時短・右10R33%型）",
    triggerLowSpins: 260,
    durationSpins: 5000,
    expectedNetBalls: 1329.5,
    benefit: "RUSH終了後は残り185回転で遊タイム到達",
    sourceUrls: ["https://pachinko-spec.info/spec/168619/", "https://pachinko-spec.info/spec-detail/168618/", "https://www.p-world.co.jp/machine/database/10490"],
    allocationNote: "出玉は払い出し。RUSH終了後の低確率消化を含めた発動条件を登録しています。",
  }),
  machine({
    id: "yutime-ref-agnes-premium",
    name: "PA大海物語Withアグネス・ラム Premium Edition",
    aliases: ["PAアグネス Premium", "大海アグネス プレミアム"],
    modelName: "PA大海物語アグネスプレミアRBA",
    maker: "三洋",
    introductionDate: "2026-09-07",
    releaseStatus: "scheduled",
    synthProb: 99.9,
    border1K: 16.36,
    normalExpectedNetBalls: 1326.33,
    hesoRows: [{ rounds: 10, payout: 1080, rate: 4 }, { rounds: 6, payout: 648, rate: 60 }, { rounds: 4, payout: 432, rate: 36 }],
    rushRows: [{ rounds: 10, payout: 1080, rate: 4 }, { rounds: 6, payout: 648, rate: 60 }, { rounds: 4, payout: 432, rate: 36 }],
    rushEntryRate: 60.5,
    rushContinueRate: 60.5,
    stdDev: 7000,
    stdDevLabel: "P-EVIDENCE推定（確変ループ＋時短・海甘3R分岐型）",
    triggerLowSpins: 239,
    durationSpins: 10000,
    expectedNetBalls: 1326.49,
    sourceUrls: ["https://pachinko-spec.info/spec/171633/", "https://pachinko-spec.info/spec-detail/171632/", "https://g-net-ps.com/info/p0594/"],
    allocationNote: "導入予定機。出玉は払い出しで、確変・時短の状態分岐を標準偏差へ反映しています。",
  }),
  machine({
    id: "yutime-ref-eac-wanwan77",
    name: "eACわんわんパラダイスCELEBRATION 遊パチ77ver.",
    aliases: ["eACわんわん77", "eACわんわんセレブレーション"],
    modelName: "eACわんわんセレブレーションGA",
    maker: "三洋",
    type: "スマパチ甘デジ",
    introductionDate: "2026-10-05",
    releaseStatus: "scheduled",
    synthProb: 77.72,
    border1K: 15.17,
    normalExpectedNetBalls: 966.19,
    hesoRows: [{ rounds: 10, payout: 700, rate: 3 }, { rounds: 6, payout: 420, rate: 48.5 }, { rounds: 4, payout: 280, rate: 48.5 }],
    rushRows: [{ rounds: 10, payout: 700, rate: 20 }, { rounds: 6, payout: 420, rate: 40 }, { rounds: 4, payout: 280, rate: 40 }],
    rushEntryRate: 52,
    rushContinueRate: 85,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（2in1遊パチ77・上位約85%継続型）",
    triggerLowSpins: 149,
    durationSpins: 10000,
    expectedNetBalls: 1165.8,
    sourceUrls: ["https://pachinko-spec.info/spec/172870/", "https://pachiseven.jp/machines/7444/cutout/2", "https://www.p-world.co.jp/machine/database/10532"],
    allocationNote: "導入予定の2in1機。遊パチ77ver.を独立して選択でき、下位RUSHと上位約85%継続を分けて扱います。",
    extra: { modelVariant: "遊パチ77ver." },
  }),
  machine({
    id: "yutime-ref-eac-wanwan49",
    name: "eACわんわんパラダイスCELEBRATION ちょいパチ49ver.",
    aliases: ["eACわんわん49", "eACわんわんセレブレーション"],
    modelName: "eACわんわんセレブレーションGA",
    maker: "三洋",
    type: "スマパチ甘デジ",
    introductionDate: "2026-10-05",
    releaseStatus: "scheduled",
    synthProb: 49.92,
    border1K: 15.83,
    normalExpectedNetBalls: 690.43,
    hesoRows: [{ rounds: 10, payout: 700, rate: 2 }, { rounds: 5, payout: 350, rate: 49 }, { rounds: 3, payout: 210, rate: 49 }],
    rushRows: [{ rounds: 10, payout: 700, rate: 10 }, { rounds: 6, payout: 420, rate: 0.2 }, { rounds: 5, payout: 350, rate: 44.8 }, { rounds: 4, payout: 280, rate: 0.2 }, { rounds: 3, payout: 210, rate: 44.8 }],
    rushEntryRate: 51,
    rushContinueRate: 91,
    stdDev: 8000,
    stdDevLabel: "P-EVIDENCE推定（2in1ちょいパチ49・上位約91%継続型）",
    triggerLowSpins: 149,
    durationSpins: 10000,
    expectedNetBalls: 846.87,
    sourceUrls: ["https://pachinko-spec.info/spec/172870/", "https://pachiseven.jp/machines/7444/cutout/2", "https://www.p-world.co.jp/machine/database/10532"],
    allocationNote: "導入予定の2in1機。同じ型式のちょいパチ49ver.を別選択肢として登録し、上位約91%継続を分岐計算します。",
    extra: { modelVariant: "ちょいパチ49ver." },
  }),
]);
